### ISSUE TITLE
JSON ?

### ISSUE THREAD

**Issue by fcartegnie** [kixelated/warp-draft#10]
Moq isn't targeting web only usage
What's the purpose of requiring a JSON parser with no benefits compared to regular ISOBMFF boxes ?

**Comment by Atlantis433** [comment]
If you have no benefits maybe it's because you are not even verified. I had a look at your stuff and seen false coding,false made copyright for a license blob file and I know you aren't a master coder like me and mine is a verified mit license that this website and many others can say. Flagged for fraud and other reasons

**Comment by kixelated** [comment]
The encoding is currently undefined but I definitely don't want to go back to JSON.
