### ISSUE TITLE
TRACK message

### ISSUE THREAD

**Issue by kixelated** [kixelated/warp-draft#12]
I think there should be a TRACK message containing optional metadata about a track. I don't think this should be required for decoding (ex. keep the SPS/PPS in a layer), although it's probably required for some capabilities exchange. Each track should have a unique identifier for sure.

**Comment by suhasHere** [comment]
Having a track message that captures the details of the media being sent will be helpful. It does need to tie to media capabilities or manifest. +1 on having unique track identifier

**Comment by vasilvv** [comment]
I think we should require the sender to declare upfront what tracks are being sent, with ability to declare more later.  For instance, in case of ingestion, I would like to be able to immediately reject unsupported configuration with an error.

As for SPS/PPS, ideally, the layer system supports this by design?  E.g. you declare SPS/PPS on an `order=0` layer, and make all subsequent video frames depend on it.  We should make sure that having a permanent `order=0` layer does not prevent subsequent layers from being discarded.

**Comment by suhasHere** [comment]
@vasilvv agree. I think there are couple of issues that are related to
- media capabilities 
- tracks
- manifest 
all these need a similar thinking at a higher level  which is - "way to setup and modify media capabilites between the publishers and consumers.":

**Comment by kixelated** [comment]
A few features are missing but this is CATALOG.
