### ISSUE TITLE
Protocol name :D

### ISSUE THREAD

**Issue by kpugin** [kixelated/warp-draft#23]
Have we settled on Warp as a name for protocol? Or should we use RUSH as we discussed on one of the calls?

**Comment by afrind** [comment]
SHWARP

From: kpugin ***@***.***>
Reply-To: kixelated/warp-draft ***@***.***>
Date: Monday, October 24, 2022 at 11:11 AM
To: kixelated/warp-draft ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kixelated/warp-draft] Protocol name :D (Issue #23)

Have we settled on Warp as a name for protocol? Or should we use RUSH as we discussed on one of the calls? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
ZjQcmQRYFpfptBannerEnd

Have we settled on Warp as a name for protocol? Or should we use RUSH as we discussed on one of the calls?

**Comment by kixelated** [comment]
Dunno, naming is hard.

I was keeping it as Warp until the RUSH folks approved the base draft but maybe we see what the WG thinks. Both RUSH and WARP are four letter fake acronyms with a speedy context (like QUIC), so I like both of them. 

The upside of Warp is that it describes the intended user behavior. Video will freeze/stutter until it "warps" forward at the next i-frame. The downside is that it's a common name. It should be capitalized like WARP at the very least.

Technically RUSH stands for  `Reliable (unreliable) streaming protocol`... although that would be "RUSP" so we'll have to fix that anyway.

**Comment by suhasHere** [comment]
not to say, quic, quicr, quicst ;)

**Comment by afrind** [comment]
The name we pick could very likely be replaced with "moq" anyways.  See what happened with QCRAM -> QPACK.

**Comment by LPardue** [comment]
How about WASH?

**Comment by suhasHere** [comment]
how about CIUQ ( sounds very similar to QUIC) !!!

**Comment by maxstoller** [comment]
@kixelated 
> It should be capitalized like WARP at the very least.

What is the though behind all caps if it is not an acronym like RUSH?

**Comment by kixelated** [comment]
> @kixelated
> 
> > It should be capitalized like WARP at the very least.
> 
> What is the though behind all caps if it is not an acronym like RUSH?

IETF likes acronyms... even if they don't actually stand for anything (ex. QUIC).

**Comment by suhasHere** [comment]
FAST - **F**ast **AS**ynchronous media **T**ransport  :-)

**Comment by afrind** [comment]
Discussed on authors call: recommendation was moq-transport

**Comment by afrind** [comment]
Now tracked in #142
