### ISSUE TITLE
Cancellation

### ISSUE THREAD

**Issue by afrind** [kixelated/warp-draft#26]
> QUIC streams can be canceled by either endpoint with an error code.

This isn't really true.  QUIC streams can be canceled only by the sender.  A receiver can request that a stream be reset.  To that end, I'm not sure how much value sending an `expires` value is, other than to inform the receiver that the sender plans to reset the stream if it's not completely sent and ack'd by then.  Should the receiver send a STOP_SENDING after expires to request a reset also or is that redundant?

**Comment by kixelated** [comment]
I can change the language around STOP_SENDING. You're right that it technically doesn't cancel the stream... although it does in effect.

The previous version of the draft had an `expires` and `cache` field in the HEADERS. The intent was to inform the relay on how long a stream should be held in memory before it was dropped and reset.

The original idea is that the broadcaster and/or consumer would be responsible for knowing when a stream is no longer desired. This would involve sending a RESET_STREAM or STOP_SENDING respectively. However this breaks down when relays are involved, as they lack this information. For example, a broadcaster could transfer a stream in its entirety to a relay, which then keeps it buffered in memory, but doesn't know when to issue a RESET_STREAM to any consumers.

But I removed it from the draft because I'm not really sure how to deal with timestamps. Sending a duration on the wire is problematic because it only starts counting down when the first stream chunk has been received and processed. This is exacerbated by `order` since it can starve streams. This is not so much a problem for `cache` but it's a huge issue for `expires`, if the intention is to reset streams in response to congestion.
