### ISSUE TITLE
APP message

### ISSUE THREAD

**Issue by afrind** [kixelated/warp-draft#28]
This sounds a bit like an extension that just gets forwarded when not understood by a relay?  How does APP interact with caches, for example?  Can a single QUIC stream have SEGMENT and APP data interleaved?

Might be too vague to leave in

**Comment by kixelated** [comment]
The intention was to cache/forward it the same way as media. It's just meant for arbitrary metadata and as a replacement for the current approach of shoving metadata into the media bitstream. For example, in h.264 land it's common to put arbitrary content (non-standardized) in SEI messages.

Even if we don't cache/forward the stream, it would still be nice to let the application use unidirectional streams. This basically says prefix the stream with a 2 if it's used by the application instead of Warp. This wouldn't work with relays which is why I had the idea of reusing HEADERS to tell the relay which application streams should be forwarded/cached and how.

**Comment by kixelated** [comment]
Oh and it's missing because there's no encoding yet, but I was envisioning that SEGMENT and APP frames do not specify a length. They would consume the remainder of the stream.

**Comment by vasilvv** [comment]
Is there an MP4 box that we can just use as a part of the layer?  That would provide some form of uniformity.

**Comment by kixelated** [comment]
> Is there an MP4 box that we can just use as a part of the layer? That would provide some form of uniformity.

That was my thought too, although it means every container will need some way of specifying application data.

**Comment by fluffy** [comment]
the RTCP APP message never turned out to be as useful in RTP as people thought it would be ...  that said, fan of being able to send whatever data in the payload. If it happens to be a protobuf app message instead of media, seem like MOQ shoudl not care, it should just deliver the bytes with not much care if they are audio, vidie, haptics, or an app custom media

**Comment by VMatrix1900** [comment]
We need to define the difference of APP message and Media data in terms of what is inside and how it is interacted with caching and dropping. Otherwise there is a risk that the APP message becomes the container for “whatever does not fit in the current RFC“  which renders the standard useless.
