### ISSUE TITLE
Producer Rendition Selection

### ISSUE THREAD

**Issue by kixelated** [kixelated/warp-draft#6]
The current draft has a brief section on ABR. The claim is that the producer should choose renditions because it has better insight into the state of the network.

Does the producer have enough information to choose the rendition, and should any additional information required be part of the protocol? For example, the current buffer size.

Additionally, should the consumer influence the decision? For example, the player is muted/backgrounded and we should save bandwidth by choosing from lower renditions.

**Comment by VMatrix1900** [comment]
Those two questions are related.
Consumer should influence the decision because:
1. consumer has the final judgement of the QoE. Sending the QoE metric back to the producer can help the sender-side optimization. One exmaple is [xlink for multi-path transport](http://www.hongqiangliu.com/uploads/5/2/7/4/52747939/sigcomm2021-xlink.pdf). For single path, reporting the application layer buffer size would be helpful too. 
2. consumer application behavior may influence the QoE dramatically such as fast forwarding (which affects the application layer buffer size ) and backgrounding (which changes the QoE model).

Those metric/behavior can not be inferred from simple ACKs of transport layer. It would be great that the protocol can provide an application-layer feedback channel from the consumer to the producer.

**Comment by acbegen** [comment]
> The current draft has a brief section on ABR. The claim is that the producer should choose renditions because it has better insight into the state of the network.

I don't agree with this claim as I mentioned before. There are a lot of things that do happen on the client side that the sender will never be aware of unless it is explicitly told by the client. Either the client provides all the other relevant details (some were listed by you and @VMatrix1900) to the sender so it can do a better decision or the sender tells the client what the current network conditions are and the client makes the decision and reports back to the sender.

**Comment by kixelated** [comment]
Yeah, I think I should remove this section. It's too much of an opinion rather than something to act upon. I just wanted a soapbox to complain about low-latency client-side ABR.

**Comment by kixelated** [comment]
Closing because the new draft does not specify track management yet. The plan is to support contribution and distribution.
